[environment]
cpu_count = 24
exec_env = "singularity"
free_mem = 71.9
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.10.0"
templateflow_version = "25.0.4"
version = "25.2.5"

[execution]
bids_dir = "<BIDS_ROOT>"
bids_database_dir = "<WORK_ROOT>/20260830-120517_bfaa756a-8081-4cb6-b118-30a1a9e4c516/bids_db"
bids_description_hash = "ed0563fc103f89cfd2b2c2c228aed2d82c352c29739cedd8c3d306fd794235c7"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "<OUTPUT_ROOT>"
fs_license_file = "<FREESURFER_LICENSE>"
fs_subjects_dir = "<FREESURFER_SUBJECTS_DIR>"
layout = "BIDS Layout: ...<BIDS_ROOT> | Subjects: 22 | Sessions: 22 | Runs: 0"
log_dir = "<OUTPUT_ROOT>/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = true
track_carbon = false
country_code = "CAN"
output_dir = "<OUTPUT_ROOT>"
me_output_echos = false
aggr_ses_reports = 4
output_layout = "bids"
output_spaces = "MNI152NLin2009cAsym:res-2 T1w"
reports_only = false
run_uuid = "20260830-120517_bfaa756a-8081-4cb6-b118-30a1a9e4c516"
processing_groups = [ "sub-01_ses-02fmri", "sub-02_ses-02fmri", "sub-03_ses-02fmri", "sub-04_ses-02fmri", "sub-05_ses-02fmri", "sub-06_ses-02fmri", "sub-07_ses-02fmri", "sub-08_ses-02fmri", "sub-09_ses-02fmri", "sub-10_ses-02fmri", "sub-11_ses-02fmri", "sub-12_ses-02fmri", "sub-13_ses-02fmri", "sub-14_ses-02fmri", "sub-15_ses-02fmri", "sub-17_ses-02fmri", "sub-18_ses-02fmri", "sub-19_ses-02fmri", "sub-20_ses-02fmri", "sub-21_ses-02fmri", "sub-22_ses-02fmri", "sub-23_ses-02fmri",]
participant_label = [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "17", "18", "19", "20", "21", "22", "23",]
templateflow_home = "<TEMPLATEFLOW_ROOT>"
work_dir = "<WORK_ROOT>"
write_graph = false

[workflow]
anat_only = false
bold2anat_dof = 6
bold2anat_init = "t1w"
cifti_output = false
fmap_bspline = false
force_syn = false
hires = true
fs_no_resume = true
ignore = []
force = []
level = "full"
run_msmsulc = true
medial_surface_nan = false
project_goodvoxels = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
slice_time_ref = 0.5
spaces = "MNI152NLin2009cAsym:res-2 T1w"
subject_anatomical_reference = "first-lex"
track_sessions = true
use_syn_sdc = "warn"
me_t2s_fit_method = "curvefit"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
memory_gb = 64.0
nprocs = 16
omp_nthreads = 8
plugin = "MultiProc"
remove_unnecessary_outputs = true
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 9136
ants = 39175
numpy = 35086

[execution.derivatives]

[execution.dataset_links]
raw = "<BIDS_ROOT>"
templateflow = "<TEMPLATEFLOW_ROOT>"

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
